services:
  - type: web
    name: imperiya-vkusa-api
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python seed_db.py && uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: ADMIN_USERNAME
        value: Абдулбасир
      - key: ADMIN_PASSWORD
        value: "19102007"
      - key: CORS_ORIGINS
        value: https://imperiya-vkusa.surge.sh
        sync: false